//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class GMRSDBEntities1 : DbContext
{
    public GMRSDBEntities1()
        : base("name=GMRSDBEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Category> Category { get; set; }
    public virtual DbSet<Data> Data { get; set; }
    public virtual DbSet<DataCategory> DataCategory { get; set; }
    public virtual DbSet<ValueType> ValueType { get; set; }
}
